version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - data_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - data_wp:/var/www/html
      - ./example-data:/var/www/data
      - ./plugin-i4embed:/var/www/html/wp-content/plugins/i4embed
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  data_db: {}
  data_wp: {}
